import UserNotifications

enum LocalNotificationPoster {
    private static let tag = "LocalNotificationPoster"

    /// Create a local notification manually (as opposed to a remote notification being generated by Firebase). We need to make the
    /// local notification look exactly like the remote one (same userInfo), so that when we tap it, the userNotificationCenter(didReceive)
    /// function has the same information available.
    static func show(baseUrl: String, message: Message, completionHandler: (() -> Void)? = nil) {
        let user = Store.shared.getUser(baseUrl: baseUrl)?.toBasicUser()
        let content = UNMutableNotificationContent()
        content.modify(message: message, baseUrl: baseUrl)
        content.attachImageIfNeeded(message: message, user: user) {
            let request = UNNotificationRequest(identifier: message.id, content: content, trigger: nil /* now */)
            UNUserNotificationCenter.current().add(request) { error in
                if let error = error {
                    Log.e(tag, "Unable to create notification", error)
                }
                completionHandler?()
            }
        }
    }

    static func showSequentially(baseUrl: String, messages: [Message], completionHandler: @escaping () -> Void) {
        guard let firstMessage = messages.first else {
            completionHandler()
            return
        }

        show(baseUrl: baseUrl, message: firstMessage) {
            showSequentially(
                baseUrl: baseUrl,
                messages: Array(messages.dropFirst()),
                completionHandler: completionHandler
            )
        }
    }
}
